server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_managementProductGraphQl?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  graphql:
    date:
      format: yyyy-MM-dd HH:mm:ss
    graphiql:
      enabled: true
logging:
  level:
    org.springframework.web: DEBUG
    ma.formation.webService.graphQl: DEBUG
